version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    networks:
      - mynetwork
    ports:
      - "5000:5000"
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mynetwork
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
