#uygulama  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
       app: mongo-app  
  template:
    metadata:
      labels:
        app: mongo-app 
    spec:
      containers:
        - name: python-app
          image: barkinatici/kubernetes  
          ports:
            - containerPort: 5000  
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/mydatabase"  
---
#app service uygulama açılıcak port 
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: mongo-app  
  ports:
    - name: app-port
      protocol: TCP
      port: 5000  
      targetPort: 5000  
---

apiVersion: v1
kind: Service
metadata:
  name: python-app-node-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80         # Kubernetes içinde kullanılacak port
      targetPort: 8080 # Pod'larınızda çalışacak uygulamanın portu
      nodePort: 30080  # Dışarıdan erişim sağlanacak port
  type: NodePort       
