name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Build Docker image (optional, if you want to build Docker image)
    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    # 5. Deploy MongoDB (if necessary, could be omitted depending on your setup)
    - name: Deploy MongoDB
      run: |
        kubectl apply -f mongodb-deployment.yaml

    # 6. Deploy Python App (if necessary, could be omitted depending on your setup)
    - name: Deploy Python App
      run: |
        kubectl apply -f python-app-deployment.yaml
