name: CI CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  
    
    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Build Docker image (optional, if you want to build Docker image)
    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    # 2. Install Minikube
    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo chmod +x minikube
        sudo mv minikube /usr/local/bin

    # 3. Start Minikube
    - name: Start Minikube
      run: |
        minikube start


        
    # 5. Deploy MongoDB
    - name: Deploy MongoDB
      run: |
        kubectl apply -f mongodb-deployment.yaml

     # 9. Wait for MongoDB pod to be in Running state
    #- name: Wait for MongoDB pod to be Running
    #  run: |
     #   kubectl wait --for=condition=ready pod -l app=mongodb --timeout=300s
        
    - name: test
      run: |
        echo "MongoDB deployment'i kontrol ediliyor..."
        kubectl rollout status deployment mongodb-deployment --timeout=1000s
        
    - name: test2
      run: |
        echo "MongoDB deployment'i kontrol ediliyor..."
        kubectl get pods


