name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Install Minikube
    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo chmod +x minikube
        sudo mv minikube /usr/local/bin

    # 3. Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker

    # 4. Set up kubectl with Minikube's kubeconfig
    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        minikube kubectl -- get kubeconfig > $HOME/.kube/config  # Minikube'dan kubeconfig al
        chmod 600 $HOME/.kube/config  # Kubeconfig dosyasına doğru izinleri ver

    # 5. Deploy MongoDB
    - name: Deploy MongoDB
      run: |
        kubectl apply -f mongodb-deployment.yaml

    # 6. Deploy Python App
    - name: Deploy Python App
      run: |
        kubectl apply -f python-app-deployment.yaml
