name: CI CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

   
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   
    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    
    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo chmod +x minikube
        sudo mv minikube /usr/local/bin

    
    - name: Start Minikube
      run: |
        minikube start


        
    
    - name: Deploy MongoDB
      run: |
        kubectl apply -f mongodb-deployment.yaml
        echo "MongoDB deployment'i kontrol ediliyor..."
        kubectl rollout status deployment mongodb-deployment --timeout=1000s

        
        
    - name: App Deployment
      run: |
        
        echo "MongoDB Pod'lari hazir.App deployment hazirlaniyor"
        kubectl apply -f python-app-deployment.yaml
        echo "Uygulama bekleniyor"
        kubectl rollout status deployment python-app-deployment --timeout=600s
        
    - name: test
      run: |
        echo "Uygulama başariyla ayağa kaldirildi."
        kubectl get pods
    - name: Get Minikube IP
      run: |
       MINIKUBE_IP=$(minikube ip)
       echo "Minikube IP: $MINIKUBE_IP"
       echo "Uygulama, http://$MINIKUBE_IP:30080 üzerinden erişilebilir."



        

